### ISSUE TITLE
config.doCrosstalk = False needs to be added to imsim/isr.py

### ISSUE THREAD

**Issue by johannct** [lsst/obs_lsst#50]
This is a consequence of switching it on by default in tag w.2018.39-run1.2-v3

**Comment by heather999** [comment]
Does it need to be isr.py or is processCcd.py sufficient?
https://github.com/lsst/obs_lsst/blob/w.2018.39-run1.2-v3/config/imsim/processCcd.py#L1

**Comment by TallJimbo** [comment]
Best practice is to add it to an `isr.py` and load that file in `processCcd.py`; not following that pattern can lead to confusion later (although I admit that's less likely to occur with `isr.py` than other Tasks).

**Comment by heather999** [comment]
@TallJimbo & @RobertLuptonTheGood Two questions:
It appears the default for isr.doCrosstalk is False, unless we explicitly set it to True in `obs_lsst/config/isr.py` Are we agreed that crosstalk should be enabled by default, for not only phosim, but presumably any other users of obs_lsst? (imsim is another matter, I'm just wondering about aux telescope, camera data..)  If it is ok, I'll update `config/isr.py` to set `isr.doCrosstalk=True`.
Second, in the case of imsim, we will want doCrosstalk set to False.  We have `config/imsim/isr.py` but to use it, do I understand correctly we will have to either modify `config/processCcd.py` to check the mapper and then pick up the `config/imsim/isr.py`if it exists or explicitly update `config/processCcd.py` locally to pick up `config/imsim/isr.py` rather than `config/isr.py`? The way I read this exchange, it sounded as though couldn't use the mapper information in the config? https://lsstc.slack.com/archives/C978LTJGN/p1543505461586800?thread_ts=1543502411.577400&cid=C978LTJGN

**Comment by TallJimbo** [comment]
There is another level of specialization: you should be able to put the option in e.g. `obs_lsst/config/phosim/isr.py` (along with a `processCcd.py` in the same directory) to enable it for just phosim.  The phosim-specific options will be loaded after and override obs_lsst-level options.

**Comment by heather999** [comment]
right I was neglectful in omitting that. But from what I can see, just creating `obs_lsst/config/phosim/isr.py`  and adding the line `config.doCrosstalk=True` does not result in that config being picked up.  I set up a test area and set up my _mapper to contain: `lsst.obs.lsst.phosim.PhosimMapper`
then ran:

``` processCcd.py /global/cscratch1/sd/desc/DC2/ALCF_Run1.2i/newcalibration/phosimTest --rerun testConfig --show history=isr.doCrosstalk
root INFO: Loading config overrride file '/global/cscratch1/sd/desc/DC2/ALCF_Run1.2i/newcalibration/testing/obs_lsst/config/processCcd.py'
isr.doCrosstalk
False /cvmfs/sw.lsst.eu/linux-x86_64/lsst_distrib/w_2018_39/stack/miniconda3-4.5.4-fcd27eb/Linux64/pipe_tasks/16.0-18-g95848a16+2/bin/processCcd.py:25 ProcessCcdTask.parseAndRun()
      pipe/base/cmdLineTask.py:597                                                                                            
      pex/config/configurableField.py:275                                                                                     
      pex/config/configurableField.py:275                                                                                     
      ip/isr/isrTask.py:240                                                                                                   
False /cvmfs/sw.lsst.eu/linux-x86_64/lsst_distrib/w_2018_39/stack/miniconda3-4.5.4-fcd27eb/Linux64/pipe_tasks/16.0-18-g95848a16+2/bin/processCcd.py:25 ProcessCcdTask.parseAndRun()
      pipe/base/cmdLineTask.py:597                                                                                            
      pex/config/configurableField.py:275                                                                                     
      pex/config/configurableField.py:275```
`config/processCcd.py` contains:
```obsConfigDir = os.path.join(getPackageDir("obs_lsst"), "config")
The same result occurs if I switch my repo to imsim and attempt to pick up `config/imsim/isr.py`
config.isr.load(os.path.join(obsConfigDir, "isr.py"))
``` This is the part I'm confused about - how would it know to pick up `config/phosim/isr.py`?

**Comment by TallJimbo** [comment]
What you want to do is add a `config/phosim/processCcd.py` *too* and have it do something like:
```
config.isr.load(os.path.join(obsConfigDir, "phosim", "isr.py"))
```
You may also need a `singleFrameDriver.py` in `config/phosim` if you're using that; the system will automatically pick up the config files in both directories that correspond directly to the Task you're actually running, but not the ones below that.

**Comment by heather999** [comment]
There is now a PR #51 which handles the setting of `isr.doCrosstalk` for both `processCcd` and `singleFrameDriver.py` strictly for imsim and phosim processing.  These changes will also be added to the `dc2/run1.2-v3` branch

**Comment by heather999** [comment]
We've moved beyond the need for doCrosstalk=False and have added explicit setting of doCrosstalk for imSim and phoSim.  Closing issue.
